# v8 adds restart policies
version: '3.7'

services:
  
  signup-db:
    image: dwwx/signup-db
    volumes:
      - C:\mssql:C:\data
    environment:
      - sa_password=DockerCon!!!
    networks:
      - app-net
    restart: always

  signup-web:
    image: dwwx/signup-web:v3
    environment: 
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
      - Dependencies:IReferenceDataLoader=SignUp.Web.ReferenceData.ApiReferenceDataLoader
      - ReferenceDataApi:Url=http://reference-data-api/api
      - Dependencies:IProspectSaveHandler=SignUp.Web.ProspectSave.AsynchronousProspectSaveHandler
    labels:
      - "traefik.frontend.rule=PathPrefix:/app"
      - "traefik.frontend.priority=30"
    depends_on:
      - signup-db
      - reference-data-api
    networks:
      - app-net
    restart: always

  homepage:
    image: dwwx/homepage
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.frontend.priority=10"
    networks:
      - app-net
    restart: always

  proxy:
    image: dwwx/reverse-proxy
    command: --docker --docker.endpoint=npipe:////./pipe/docker_engine --docker.watch --api
    ports:
      - "8020:80"
      - "8080:8080"
    volumes:
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine      
    networks:
      - app-net
    restart: always

  reference-data-api:
    image: dwwx/reference-data-api
    environment: 
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
    labels:
      - "traefik.frontend.rule=PathPrefix:/api"
      - "traefik.frontend.priority=20"
    depends_on:
      - signup-db
    networks:
      - app-net
    restart: always

  message-queue:
    image: dwwx/message-queue
    networks:
      - app-net
    restart: always

  signup-save-handler:
    image: dwwx/save-handler:v2
    environment: 
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
    depends_on:
      - signup-db
      - message-queue
    networks:
      - app-net
    restart: always

  signup-index-handler:
    image: dwwx/index-handler:v2
    depends_on:
      - elasticsearch
      - message-queue
    networks:
      - app-net
    restart: always

  elasticsearch:
    image: sixeyed/elasticsearch:5.6.11-windowsservercore-ltsc2019
    volumes:
      - C:\es:C:\data
    networks:
      - app-net
    restart: unless-stopped

  kibana:
    image: sixeyed/kibana:5.6.11-windowsservercore-ltsc2019
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-net
    restart: unless-stopped

  prometheus:
    image: dwwx/prometheus
    volumes:
      - C:\prom:C:\prometheus
    ports:
      - "9090:9090"
    networks:
      - app-net
    restart: unless-stopped

  grafana:
    image: dwwx/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:
    external:
      name: nat